### ISSUE TITLE
Base Visualization options its empty?

### ISSUE THREAD

**Issue by RitaAguiar** [rileymd88/qwik-trellis#1]
Hello, I have just installed Qwik Trellis and I cannot change the Base Visualization option.
What may be causing this issue?
Thank you.

![qwik trellis 2](https://user-images.githubusercontent.com/44228423/53165131-d503b780-35c9-11e9-8aa8-ce5ecdf581ae.gif)

**Comment by rileymd88** [comment]
Hello - For this extension to work you first need to create your master visualization and then you will be able to select your master visualization from the drop down:  https://help.qlik.com/en-US/sense/November2017/Subsystems/Hub/Content/Visualizations/create-master-visualization.htm 

Also a note since I see you are using Qlik Sense Desktop, at the moment there is a bug where the charts will not render when viewing the extension within the Desktop Client, it does however work in the browser so if you go to http://localhost:4848/hub/ and then open your app from there everything should work

**Comment by RitaAguiar** [comment]
Thank you! I got it to do what I wanted 🙂
A super Graphic divided in several graphics to show 3 dimensions + 1 measure.

[cid:b397d15a-abdc-4b53-9afc-d6bc034c49ff]

________________________________
De: rileymd88 <notifications@github.com>
Enviado: 21 de fevereiro de 2019 11:31
Para: rileymd88/qwik-trellis
Cc: RitaAguiar; Author
Assunto: Re: [rileymd88/qwik-trellis] Base Visualization options its empty? (#1)


Hello - For this extension to work you first need to create your master visualization and then you will be able to select your master visualization from the drop down: https://help.qlik.com/en-US/sense/November2017/Subsystems/Hub/Content/Visualizations/create-master-visualization.htm

Also a note since I see you are using Qlik Sense Desktop, at the moment there is a bug where the charts will not render when viewing the extension within the Desktop Client, it does however work in the browser so if you go to http://localhost:4848/hub/ and then open your app from there everything should work

**Comment by RitaAguiar** [comment]
Following the previous message. I have a suggestion: I think it would be greatly advantageous if your Trellis Chart could be a single chart, where you have 2 dimension on the x axis, a 3rd dimension stacked and 1 measure in the height (instead of splitting the 3rd dimension in several graphics). Hopping you may consider this. Thank you, your extension is very helpful!

________________________________
De: rileymd88 <notifications@github.com>
Enviado: 21 de fevereiro de 2019 11:31
Para: rileymd88/qwik-trellis
Cc: RitaAguiar; Author
Assunto: Re: [rileymd88/qwik-trellis] Base Visualization options its empty? (#1)


Hello - For this extension to work you first need to create your master visualization and then you will be able to select your master visualization from the drop down: https://help.qlik.com/en-US/sense/November2017/Subsystems/Hub/Content/Visualizations/create-master-visualization.htm

Also a note since I see you are using Qlik Sense Desktop, at the moment there is a bug where the charts will not render when viewing the extension within the Desktop Client, it does however work in the browser so if you go to http://localhost:4848/hub/ and then open your app from there everything should work
