### ISSUE TITLE
Extension not working after dragging

### ISSUE THREAD

**Issue by smandar** [rileymd88/qwik-trellis#5]
![Capture](https://user-images.githubusercontent.com/6689855/60235008-f5b78300-98c3-11e9-855a-2f9c29d50005.PNG)

Im facing following issue while working with extension. It has  imported but not getting displayed the moment i drag in app . 
Given console  is nothing but my browser screenshot.

**Comment by rileymd88** [comment]
Hi Smandar - I am not activly maintaining this extension as it has been integrated as a bundled extension into qlik sense. You can either download the new June 2019 release to use it or download it from the qlik-oss github here: https://github.com/qlik-oss/qwik-trellis/releases/download/0.25.0/qlik-trellis-container_0.25.0.zip
